# Generated by Django 3.2 on 2021-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_auto_20210502_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowval', models.IntegerField()),
                ('colval', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
