# Generated by Django 3.2 on 2021-05-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0004_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkslots',
            name='carid',
            field=models.CharField(max_length=10),
        ),
    ]
