# Generated by Django 3.2 on 2021-05-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0005_alter_parkslots_carid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freeslots',
            unique_together={('rowval', 'colval')},
        ),
        migrations.AlterModelTable(
            name='freeslots',
            table='Freeslots',
        ),
    ]
