# Generated by Django 3.2 on 2021-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0006_auto_20210511_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=10)),
                ('phnnum', models.IntegerField()),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
